2021-03-20 08:33:50,318 ERROR: Exception on /reset_password_request [GET] [in /Users/patrickchong/Desktop/microblog3/venv/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/Users/patrickchong/Desktop/microblog3/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/patrickchong/Desktop/microblog3/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/patrickchong/Desktop/microblog3/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/patrickchong/Desktop/microblog3/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/patrickchong/Desktop/microblog3/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/patrickchong/Desktop/microblog3/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/patrickchong/Desktop/microblog3/app/routes.py", line 178, in reset_password_request
    title='Reset Password', form=form)
  File "/Users/patrickchong/Desktop/microblog3/venv/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/Users/patrickchong/Desktop/microblog3/venv/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/patrickchong/Desktop/microblog3/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/patrickchong/Desktop/microblog3/venv/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/patrickchong/Desktop/microblog3/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/patrickchong/Desktop/microblog3/app/templates/reset_password_request.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/patrickchong/Desktop/microblog3/app/templates/base.html", line 31, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/patrickchong/Desktop/microblog3/app/templates/reset_password_request.html", line 8, in block "content"
    {{ form.password.label }}<br>
  File "/Users/patrickchong/Desktop/microblog3/venv/lib/python3.7/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'app.forms.ResetPasswordRequestForm object' has no attribute 'password'
2021-03-20 08:36:17,780 INFO: Microblog startup [in /Users/patrickchong/Desktop/microblog3/app/__init__.py:48]
2021-03-20 08:50:19,638 INFO: Microblog startup [in /Users/patrickchong/Desktop/microblog3/app/__init__.py:50]
2021-03-20 08:51:35,355 INFO: Microblog startup [in /Users/patrickchong/Desktop/microblog3/app/__init__.py:50]
2021-03-20 08:52:34,631 INFO: Microblog startup [in /Users/patrickchong/Desktop/microblog3/app/__init__.py:50]
2021-03-20 08:54:43,245 INFO: Microblog startup [in /Users/patrickchong/Desktop/microblog3/app/__init__.py:50]
2021-03-20 08:56:37,872 INFO: Microblog startup [in /Users/patrickchong/Desktop/microblog3/app/__init__.py:50]
2021-03-20 08:59:28,434 INFO: Microblog startup [in /Users/patrickchong/Desktop/microblog3/app/__init__.py:47]
2021-03-21 11:52:24,396 INFO: Microblog startup [in /Users/patrickchong/Desktop/microblog3/app/__init__.py:49]
2021-03-21 11:52:28,181 ERROR: Exception on /login [GET] [in /Users/patrickchong/Desktop/microblog3/venv/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/Users/patrickchong/Desktop/microblog3/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/patrickchong/Desktop/microblog3/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/patrickchong/Desktop/microblog3/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/patrickchong/Desktop/microblog3/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/patrickchong/Desktop/microblog3/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/patrickchong/Desktop/microblog3/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/patrickchong/Desktop/microblog3/app/routes.py", line 71, in login
    return render_template('login.html', title='Sign In', form=form)
  File "/Users/patrickchong/Desktop/microblog3/venv/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/Users/patrickchong/Desktop/microblog3/venv/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/patrickchong/Desktop/microblog3/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/patrickchong/Desktop/microblog3/venv/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/patrickchong/Desktop/microblog3/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/patrickchong/Desktop/microblog3/app/templates/login.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "/Users/patrickchong/Desktop/microblog3/venv/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/patrickchong/Desktop/microblog3/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/patrickchong/Desktop/microblog3/app/templates/base.html", line 53, in template
    {% endblock %}
jinja2.exceptions.TemplateSyntaxError: Unexpected end of template. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2021-03-21 11:52:28,348 ERROR: Exception on /login [GET] [in /Users/patrickchong/Desktop/microblog3/venv/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/Users/patrickchong/Desktop/microblog3/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/patrickchong/Desktop/microblog3/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/patrickchong/Desktop/microblog3/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/patrickchong/Desktop/microblog3/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/patrickchong/Desktop/microblog3/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/patrickchong/Desktop/microblog3/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/patrickchong/Desktop/microblog3/app/routes.py", line 71, in login
    return render_template('login.html', title='Sign In', form=form)
  File "/Users/patrickchong/Desktop/microblog3/venv/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/Users/patrickchong/Desktop/microblog3/venv/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/patrickchong/Desktop/microblog3/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/patrickchong/Desktop/microblog3/venv/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/patrickchong/Desktop/microblog3/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/patrickchong/Desktop/microblog3/app/templates/login.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "/Users/patrickchong/Desktop/microblog3/venv/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/patrickchong/Desktop/microblog3/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/patrickchong/Desktop/microblog3/app/templates/base.html", line 53, in template
    {% endblock %}
jinja2.exceptions.TemplateSyntaxError: Unexpected end of template. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2021-03-21 11:54:11,545 INFO: Microblog startup [in /Users/patrickchong/Desktop/microblog3/app/__init__.py:49]
2021-03-21 11:55:32,244 INFO: Microblog startup [in /Users/patrickchong/Desktop/microblog3/app/__init__.py:49]
2021-03-22 14:15:53,663 INFO: Microblog startup [in /Users/patrickchong/Desktop/microblog3/app/__init__.py:49]
2021-03-24 15:35:32,082 INFO: Microblog startup [in /Users/patrickchong/Desktop/microblog3/app/__init__.py:55]
2021-03-24 15:35:32,084 INFO: Microblog startup [in /Users/patrickchong/Desktop/microblog3/app/__init__.py:69]
2021-03-24 15:35:32,084 INFO: Microblog startup [in /Users/patrickchong/Desktop/microblog3/app/__init__.py:69]
